baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng-me"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Website for Lee Wallace"
  keywords = "homepage, student, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "Lee Wallace"
    homeSubtitle = "Student | (London, UK)"
    subtitle = ""
    keywords = ""
    copyright = "Lee Wallace"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "|"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
    
    disable404 = true
    disableRSS = true
    enableRobotsTXT = true
    enableEmoji = true
    
    [author]
  Location = "London, UK"
  Email = "hello@leewallace.me"
    

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "Journal"
        name = "Journal"
        url = "https://journal.leewallace.me"
      [[languages.en.menu.main]]
	identifier = "FYP"
	name = "FYP"
	url = "/"

 # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/leepjwallace/"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/leewallacee/"

  [[params.social]]
    name = "email"
    url  = "mailto:hello@leewallace.me"

  [[params.social]]
    name = "github"
    url  = "https://github.com/WallaceDevelopment/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/leepjwallace/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "journal"
    name       = "Journal"
    url        = "https://journal.leewallace.me/"
  [[menu.main]]
    identifier = "FYP"
    name = "FYP"
    url = "/"
